runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static
  static_dir: restaurantfinder/static
- url: /.*
  script: main.app


- url: /static/
  static_dir: restaurantfinder/static/
  secure: always
  application_readable: true
  expiration: "90d"
  http_headers:
    X-Frame-Options: "DENY"
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"

includes:
- lib/mapreduce/include.yaml

libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest


skip_files:
  #File Types
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.p12
  - ^(.*/)?.*\.pem
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*\.scss
  - ^(.*/)?.*\.soy
  - ^(.*/)?.*\.sql
  - ^(.*/)?.*\.log
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?\.DS_Store
  - ^(.*/)?\.coveragerc
  - ^(.*/)?\.stylelintrc

  #Root Directory
  - ^libs/PIL/.*
  - ^apptests/.*
  - ^docker/.*
  - ^tests/.*
  - ^.*node_modules/.*
  - ^.src/.*
  - ^\.git/.*
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md
  - Makefile

